### ISSUE TITLE
Robot head trying to move down when initalizing

### ISSUE THREAD

**Issue by nilsbore** [strands-project/scitos_robot#17]
We had a bit of a problem with our problem when it arrived. The motor driving the "nodding" of the head was scratching the plastic bowl and we eventually realized that it had come off. The problem was probably due to the motor pulling to strongly at initialization, driving the "nodding" of the head down towards the hardware stop. This is probably a design feature to initialize the encoder at the bottom of the movement.

We have received a spare motor from metralabs and it generally seems to work now. However, it still drives the head downward at initialization, making some noise for a couple of seconds. I remember there being some noise at this step from the other robots as well. Can one of you guys check if the noise is originating from the same source? We want to make sure that our robot is working as it's supposed to and then get back to the metralab guys. Cheers!

**Comment by marc-hanheide** [comment]
@gestom @cdondrup did you hear this? I don't think I ever noticed it with Linda

**Comment by cdondrup** [comment]
Just had to restart the robot. It does make the described noise when initialising the robot. So everything should be fine.
