### ISSUE TITLE
ASUS Xtion USB id

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_robot#18]
We are going to purchase a new ASUS Xtion for our university. As there seems to be some problems with Xtions with USB id 1s27:0601 on the STRANDS robot, we are thinking of buying one with the proposed id 1s27:0600. Just wondering if there is any way to figure out the id from the model name or so to order the correct one.

**Comment by marc-hanheide** [comment]
Here's a photo of the serial numbers etc of the 0600 we got. Not sure that helps.

![img_20130918_083437](https://f.cloud.github.com/assets/1153084/1226697/9987cc62-2785-11e3-92e7-7f3a98093545.JPG)

**Comment by ghost** [comment]
We didn't buy a new one yet, however in last weeks meeting there were some discussions about fixing the problem in general and possibly contacting Asus? Is there any news on this, or should be also look into replacing it if we want to use it?

**Comment by cdondrup** [comment]
If I remember correctly, the part about contacting ASUS was to find out how to determine the USB id of the cameras before buying them. That will not fix the issue with the default camera on the robot but would allow to buy the right one to replace it.

**Comment by ghost** [comment]
Okay, so the way to go is to get a new one then, or check if we have a "correct" one in the lab. @cdondrup do I need this to get the visual docking to run? I wanted to test this yesterday, but felt a bit lost. Considering RGB or Depth do work, it should work for the docking right ?

**Comment by hawesie** [comment]
Yes, RGB is enough for docking, and I believe all sites are using the mounted ASUS RGB data  for  docking (I'm hoping this is all set up by default).

**Comment by ghost** [comment]
We tested the camera, just to confirm that it isn't working for us either. What I noticed was that the 601 model seems to run fine without any problems as long as you start it with roscore and openni. If you start it together with the scitos_bringup though, it gives the typical behaviour. Did anyone else notice this? To me it looks a bit like there isn't an actual problem with the camera, considering it does run fine without our stuff.

**Comment by cdondrup** [comment]
That is true, because the scitos bringup starts controlling all the hardware causing a lot of traffic on the USB controller. That's why we tried to switch the USB 3 on Linda to a USB 2 to put the ASUS on a different controller. Didn't help though.

**Comment by marc-hanheide** [comment]
yes, everybody observes the very same. The problem seems to be that the 0601 version requires USB BULK transport, the 0600 doesn't. It is correct that the 0601 works if only used on its own, but any other USB device connected to the USB hub will cause the error. Hence, yes, the cameras work, but there is a bug somewhere (probably in the implementation of the USB stack) that causes the different transports to interfere. The bug is NOT in the camera, the bug is wither in the USB hub or its driver, but the only way to work around that worked for us was using the 0600 version...

**Comment by ghost** [comment]
Thank you for the write up. I caught a lot of bits and pieces about this
problem, but I didn't have the big picture. So I will look around the lab
for a 0600 model then to get stuff running.

**Comment by cburbridge** [comment]
I'm closing this as I think it is old. Some solutions to the camera problem are at the top of https://github.com/strands-project/strands_management/wiki/Robot-Setup.

Everyone please feel free to reopen.
