### ISSUE TITLE
Robot's PC fails to start 

### ISSUE THREAD

**Issue by gestom** [strands-project/scitos_robot#20]
Sometimes - (approx. 20% of cases), the PC fails to start properly and gets stuck in this screen, 
![stuckscreen](https://f.cloud.github.com/assets/4293593/1368383/f49892e0-399a-11e3-8599-5cee788bff10.jpg).  The F2 and del keys do not do anything.

This requires to turn on and off the PC by means of the small control screen at the robot base - i.e. human intervention and  prevents to use a PC reboot as a "last-resort" recovery strategy. 

1) Anyone experiencing this as well?
2) @chmartin21 : Is the PC supposed not to boot reliably? Would it be possible to use a HW watchdog to resolve this issue ? Do you offer such a watchdog with SCITOS-G5 ? Is there an external signal line to reset the PC  if we wanted to make our own hardware based watchdog ?

**Comment by gestom** [comment]
Just to add an important detail: the restart is needed in case of CAN bus crash.

**Comment by chmartin21** [comment]
Of course, the SCITOS PC should boot reliably. We also noticed this problem very rarely on some of our robots. As far as I can remember, in all cases the reason for the blocked boot process was a connected USB device (receiver of a wireless key, a USB pen drive, ...). After removing the device, everything was fine.

We will try to investigate this problem in more detail. Maybe the "A2" in the bottom right corner gives us a hint.

**Comment by gestom** [comment]
Thanks! I will try to figure out which USB device is causing that.

**Comment by ToMadoRe** [comment]
Got this issue as well this morning

**Comment by gestom** [comment]
I have tried to remove all USB devices except the Kinect and  the problem still occurs from time to time. We are considering to build a small hardware watchdog, that would reset the PC in case it fails to boot. @chmartin21: Is there an external signal line to reset the robot computer ?

**Comment by chmartin21** [comment]
@gestom: Sorry, there is no such signal line. But we're working on this problem. We are in contact with our supplier, which has a good contact to the manufacturer of the mainboard.

**Comment by cburbridge** [comment]
@gestom is this still an issue?

**Comment by cdondrup** [comment]
It might have been caused by the Kinects cvonnected to the main PC but we now have both of them plugged into different PCs, therefore it didn't happen again. Will close for now and reopen if we see it again.
