### ISSUE TITLE
Robot not charging past 90% 

### ISSUE THREAD

**Issue by ghost** [strands-project/scitos_robot#22]
Our robot does not charge past 90%. It even went down from 91% to 90% while charging. This happens both with the charging station or when charging by cable.

**Comment by mzillich** [comment]
Maybe looking at the error log helps:

Christian Reuther from Metralabs wrote (my translation, without knowing what most of the words mean ..):
The robot writes to a persistent error memory, which can also be read out in miracenter.
This is how to produce the text file:
(1) Start Miracenter with a config file, that loads the SCITOS-driver, e.g. the CogniDrive configuration
(2) Get the RPC console into the foreground (CTRL+D and select "RPC  Console)
(3) call the RPC method savePersistentErrors of the robot driver RPC interface (typically "/robot/Robot" -->  /robot/Robot.savePersistentErrors), with the name of the file under which to store  as parameter
 e.g.
 /robot/Robot.savePersistentErrors("pers_errors_16_10_13.txt")

depending on the size of the error memory this can take some time
the file then is found in the directory from which you started miracenter

**Comment by ghost** [comment]
Thank you for the info. It gives quite a big log indeed, but I wasn't able to make out the real problem from it. Luckily a restart sufficed. All cells seem to be fine though, as they all have the same voltage. I will report back if it happens again.

**Comment by ghost** [comment]
Okay, so after loading it for hours now, this time it got stuck at 96%. After taking a closer look at the cell voltage, we noticed that the first cell only has 3.55V while all others are around 3.6V it isn't a big difference, but I'm wondering if this could be a cause for the problem. We'll let it charge overnight to see what happens.

**Comment by ghost** [comment]
Okay, so yesterday evening I configured it to charge to 100%, it was at 96% while the cell voltage of the one weird cell was slowly going up. I don't know if it patrolled over night, but I don't really think so. This morning my colleague arrived and said it was at 94% and then it wen down to 93%, while on the charging station.  After a restart it charged again for a little while, but I think it again went to discharging. 

What we noticed is that the on the little display, the current is typically a positive value (>1 A) while not charging. Once we put it on the charging station after a reboot, it goes down to ~ -10A. While this is the case, it charges a few percent pretty fast. However, within a short time (read minutes) the current drops to a level where it oscillates around 0A, sometimes being negative and sometimes positive. Eventually it gets worse and worse until it starts discharging while on the charging station. 

I have no idea if this is the intended behavior, but in the end it is simply not charging correctly anymore. I can't really say if this only happened after using the stickers, as we never really paid attention to it before applying them.

**Comment by ghost** [comment]
@chmartin21 Can you say anything about this? It would be good to know why this is happening and if there is some fix to it. Also @hawesie , what I forgot to ask during the meeting, do you know if anyone else is seeing similar behavior?

**Comment by hawesie** [comment]
Not that I've heard of.

**Comment by chmartin21** [comment]
This behaviour can be fixed by an update of the firmware of the charger. Unfortunately, it is not possible to update this firmware from the robot itself. Probably the easiest way would be, that we're preparing a new charger unit and send it to you. Then you can replace your charger unit with the new one and send the old one back to us. Would that okay for you? Who (which robot) wants to be the first?

The new version also allows to update the firmware directly from the robot. The Birmingham robot already got this update during the repair.

**Comment by ghost** [comment]
Does this involve sending the whole charging station around or is the charging unit just part of the robot/station?

But I guess since we have the problem feel free to get us up and running with the new unit.

**Comment by chmartin21** [comment]
@AlexanderHermans: The "charger unit" is part of the robot (not part of the charging station!). The charger unit is also responsible for the power supply. Yes, you could send the charger unit, but then you can't use robot. Therefore, we suggested that we prepare a new charger unit and you can replace it in your lab. We'll prepare a new charger unit (and some instructions) and send it to Aachen. Okay?

**Comment by lucasb-eyer** [comment]
@chmartin21: On behalf of @AlexanderHermans: Okay.

**Comment by ghost** [comment]
@chmartin21 Is there any new on this?

**Comment by marc-hanheide** [comment]
@chmartin21 Lincoln is also observing strange charging behaviour now. Our robot doesn't charge to 100% any more. In the attached figure it just made it to 95%, in another case I have seen it stuck at 97%.
![charging-profile-linda](https://f.cloud.github.com/assets/1153084/1623247/ac697582-56b1-11e3-9fed-6069988024f8.png)
The figure shows the actual current over time. At 95% the robot left the charging station. We wonder 
1. Is this pulse charging expected? Is this the regular pattern?
2. Why and when does it start to enter the trickle charge we see towards the end
3. Can we somehow know when the battery is considered full by the charger?

Thanks, Marc

**Comment by ml-stu** [comment]
Birmingham, Stockholm and Wien should have the new charger firmware (1.6.0). Here the charger should show 0% when empty and 100% when full.

Aachen will receive the new charger within the next week. After they changed the charger and sent the other one back we will prepare it for Lincoln or Leeds and so on.

**Comment by marc-hanheide** [comment]
@ml-stu Thanks! Just to confirm the current pattern observed is the expected one, is it? It is normal that it doesn't charge continuously?

**Comment by ml-stu** [comment]
In the firmware at your charger the charger temperature, cell voltage thresholds or cell voltage differences may stop charging for a while. In the newer firmware the charging current is only reduced in most cases so you will see than a continous charging.

**Comment by marc-hanheide** [comment]
Can we flash that ourselves?

**Comment by marc-hanheide** [comment]
Sorry has been answered already ;-)

**Comment by ghost** [comment]
So today we got a package from Metralabs. Like the last one, no description whatsoever. So at first we wondered. Is it a toaster? A weapon of mass destruction? Luckily our calm and logical thinking pointed us in the right direction. So the next question arose. Where do we put it? In the head? Somewhere close to the pc? After taking apart several things, which were not necessary, we finally found it. I didn't call the technical helpline, as last time I called them, nobody answered. So we unscrewed the old unit. And thanks to the fair warnings we didn't get our fingers covered in thermal grease, oh no wait we did :( So considering there was no new thermal grease, we assumed we could just use it without any? But while trying to screw the unit to the robot, we found that the holes had no winding. So we had to take the old charging unit apart, fix the backplate to the new one, (so we do have some old thermal grease after all :D) and finally put the cables back where they belong. 

The robot seems to be charging fine, but please metralabs the next time you send us something, could you maybe do a little sketch or description of what the product is and how to mount it? And more important, if you send us a package, please send us the required components. With the display the nuts were missing and this time the screw thread was missing in the back plate. That would really be great :D 

Cheers!

**Comment by chmartin21** [comment]
@all: Sorry, about the this. We will improve our processes, so that such inconveniences will not happen anymore. We don't have detailed descriptions for replacing components of the robot. In the past we learned, that it is much more easier for our customers and for us, to give support for such kind of repairs by phone or Skype. Therefore, we will put at least the contact information of an appropriate contact person of MetraLabs in the package. Again, sorry about this!

**Comment by ml-stu** [comment]
@AlexanderHermans Would you please send the old Charger back to ML so we can fix it and send it as replacement to Lincoln and Leeds?

**Comment by marc-hanheide** [comment]
Yes, please, with all thermal grease left ;-)

**Comment by ghost** [comment]
The charge is already packed into the box. I will drop it off at the post
office soon.
