### ISSUE TITLE
try/catch in driver code

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_robot#23]
The driver code needs exception handling to address issue #10.

**Comment by cburbridge** [comment]
This pull does it, the reported error is now along the lines of:

[ WARN] [1382970690.030516226]: Saw a negative time change of -9.850557 seconds, clearing the tf buffer.
[ WARN] [1382970690.350805284]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970690.804447790]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970691.057840759]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970691.311297115]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970691.564751403]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970691.818072898]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970692.071513420]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970692.325028320]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970692.578738356]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970692.832082193]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970693.085512712]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970693.339054733]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970693.592390311]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970693.845822053]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970694.099350538]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970694.352780224]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970694.606413041]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970694.859770738]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970695.113135779]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970695.366568678]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970695.619992410]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970695.873446738]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970696.126997638]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970696.380347810]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970696.633840866]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970696.887249584]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970697.140732461]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970697.394270143]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970697.647724350]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970697.901079777]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970698.154534246]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970698.407875095]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970698.661393087]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970698.915049061]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970699.168551412]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970699.422160416]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970699.675659234]: Missing head angle publication as MIRA parameter error.
[ WARN] [1382970699.897107905]: (MIRA) Invalid CRC on MetraLabs CAN-to-Serial Adapter. Is 0x79e should 0x352
[WARNING ] 2013-Oct-28 14:31:39.897008 Invalid CRC on MetraLabs CAN-to-Serial Adapter. Is 0x79e should 0x352
[ WARN] [1382970699.898783529]: (MIRA) Invalid CRC on MetraLabs CAN-to-Serial Adapter. Is 0x1a06 should 0xe08f
[WARNING ] 2013-Oct-28 14:31:39.898768 Invalid CRC on MetraLabs CAN-to-Serial Adapter. Is 0x1a06 should 0xe08f

and if / once the CAN bus recovers from its confusion things everything should still be ok....

**Comment by cburbridge** [comment]
@nilsbore @cdondrup Did anyone try this patch? Is it safe to merge?

**Comment by cdondrup** [comment]
As far as I know we didn't try. Maybe @gestom wants to test it with the current set-up of Linda over the weekend?

**Comment by gestom** [comment]
will do
