### ISSUE TITLE
move openni stuff somewhere else

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_robot#33]
We think that this is not the right repository for the openni stuff. It should go into its own repository as other people out there might want to use this independently of our very robot-specific stuff. And we also want to include it in the desktop installation, as it's not specific to the robot.

**Comment by nilsbore** [comment]
Preferably it should go into a package that's part of the desktop install since I have a pending PR for strands_morse requiring this: https://github.com/strands-project/strands_morse/pull/68#issuecomment-48454395.

**Comment by cdondrup** [comment]
Imho there is no really fitting repository for this but there are a few possibilities:
- since we have a `scitos_drivers` repo we could create a `strands_drivers` repository as well which includes hardware drivers that are not specific to the scitos robot like the openni wrapper.
- Create a `openni_wrapper` repository

Less clever alternatives:
- Move it to the "useful-node-dump" `strands_utils`
- Move it to the currently unused `vision` repository.

**Comment by hawesie** [comment]
On 9 Jul 2014, at 12:12, Christian Dondrup notifications@github.com wrote:

>   • Create a openni_wrapper repository

I think this makes the most sense to me, else having a perception or sensor tools repo.

**Comment by RaresAmbrus** [comment]
@hawesie I want to move the openni package, can you please create a new openni_wrapper repository? I don't think I have the permissions to do that. Thanks!

**Comment by hawesie** [comment]
Done, and you have full admin access to it: https://github.com/strands-project/openni_wrapper

**Comment by RaresAmbrus** [comment]
Great, thanks!

**Comment by hawesie** [comment]
Please close this when the move is complete.

**Comment by cburbridge** [comment]
done.

**Comment by marc-hanheide** [comment]
So, can we get that https://github.com/strands-project/openni_wrapper package ready for release? I added it to the devel config already in https://github.com/strands-project/rosdistro/commit/a30bb925b465e57e23ee75bf67ac778de92759a8. Let's see if it builds :-)

**Comment by RaresAmbrus** [comment]
Ok, I'll fix the package.xml tomorrow, was busy all day today setting some stuff up for a course.
