### ISSUE TITLE
Linda shuts down completely without any obvious reason

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_robot#35]
We discovered that our robot (PC and the base) shut down completely several times a day without any obvious reason. It started recently; yesterday for all we know. So far it happened three times: once in the middle of the room while patrolling and twice when she tried to dock. Before the charging started she just turned off everything.
Is there any reason why this could happen, @chmartin21 ? The battery is at 98% but she just shut down regardless.

**Comment by marc-hanheide** [comment]
Did you check the logs? E.g. Syslog?? Or the kernel?

**Comment by cdondrup** [comment]
Tom checked the logs but couldn't see anything suspicious.
The weird thing is that it's not only the PC but the whole base as well.

**Comment by chmartin21** [comment]
Please can you read out the persistent error memory of the charger? This can be done by using the corresponing TCP call.

**Comment by gestom** [comment]
Can you be more specific about the call we should use to read the memory ?

**Comment by chmartin21** [comment]
Please use getPersistentErrorCount() and getPersistentErrors() of the SCITOS unit. You also can use savePersistentErrors() to store the content of the error memory into a file. A complete list of the RPC can be found here: http://www.mira-project.org/MIRA-doc/domains/robot/SCITOS/index.html#ChargerHG2_Section

**Comment by Jailander** [comment]
This is a photo of how even the base shuts down (this is the 4th time it happened, now is five times the fifth was immediately afterwards), 

![fail](https://f.cloud.github.com/assets/5035967/2058303/c1602358-8b6a-11e3-8d59-d8fca579b2c1.jpg)

**Comment by Jailander** [comment]
This is what we get when using `/robot/Robot.savePersistentErrors("name_of_the_file.txt")`

https://docs.google.com/document/d/1Mq_4T9rYHyF84QS7ReIxvHO_I25jYaFJIo6Bo97bIYs/edit?usp=sharing

Sorry I couldn't find a way to attach a text file in the comments

**Comment by chmartin21** [comment]
We will check the content of the error memory and inform you as soon as possible.

**Comment by Jailander** [comment]
Hi, in issue #26 I left a video with an error we have been having on the charging station since this issue started, i think they can be related.

**Comment by ml-stu** [comment]
The errors look like ESD problems which cause a critical shut down of the robot. Are there some changes in the robots environment which may promote a electrostatic charge of the robot while driving?
We are prepairing a new charger module for replacement. The up to date firmware double checks the error which causes the critical shut down and should not power of on ESD.

**Comment by cburbridge** [comment]
@cdondrup Is this closable?

**Comment by Jailander** [comment]
yes I haven't seen that happening again

**Comment by cdondrup** [comment]
Did not happen again.
