### ISSUE TITLE
OpenNi2 wrapper image_view error

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_robot#38]
When trying to run image_view with the depth/image_raw

```
rosrun image_view image_view image:=/head_xtion/depth/image_raw
```

I get the following error and nothing happens

```
[ERROR] [1394539150.828771105]: Unable to convert '16UC1' image to bgr8: '[16UC1] is not a color format. but [bgr8] is. The conversion does not make sense'
```

Does anyone else have the same problem?

**Comment by RaresAmbrus** [comment]
Hi,

I haven't tried image_view, but it was working fine on rviz. Can you check like that?

Rares

**Comment by cdondrup** [comment]
It does work in rviz. Don't know why image_view fails.

**Comment by cdondrup** [comment]
See https://github.com/strands-project/scitos_robot/issues/39
