### ISSUE TITLE
Check for cliff detection for dealing with downward stairs

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_robot#5]

**Comment by hawesie** [comment]
Both TUW and KTH have issues with stairs. Did we ever find out whether or not we have a cliff sensor on the robot? (@cburbridge mentioned we might) If not, what can we do to make the robot safe in such situations? Without this it is going to be hard to do long-term runs at the aforementioned sites.

**Comment by mzillich** [comment]
right now we are doing runs in a different place without cliffs (though 
there are of course other hazards like door thresholds which let the 
robot tilt dangerously).

We could fence off the cliff, but that is not a nice solution. 
uncomfortable and there is the risk of forgetting to put the fence back.

M

**Comment by nilsbore** [comment]
@hawesie @mzillich  This has been fixed.
