### ISSUE TITLE
[pc_monitor] AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_robot#56]
When trying to run the pc_monitor I get:

```
process[pc_monitor-5]: started with pid [4704]
process[diagnostic_aggregator-6]: started with pid [4709]
process[joint_state_publisher-7]: started with pid [4731]
[ INFO] [1401964398.543195021]: Not loading with MIRA multiprocess support.
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 759, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/strands/strands_hydro_ws/src/scitos_robot/scitos_pc_monitor/src/sysmon/status_monitor.py", line 32, in _on_timer
    self.update()
  File "/opt/strands/strands_hydro_ws/src/scitos_robot/scitos_pc_monitor/src/sysmon/network_monitor.py", line 21, in update
    self._transmit_total = int(m.group(2))
AttributeError: 'NoneType' object has no attribute 'group'
```

It is launched via the scitos bringup files.

Also it hogs a lot of memory even though - or maybe because - it doesn't launch properly.

**Comment by cburbridge** [comment]
What is the name of the wireless network on Linda? I guess not 'wlan0'..

**Comment by cburbridge** [comment]
@cdondrup Please could you test with my fork: https://github.com/cburbridge/scitos_robot, branch hydro-devel. It should not crash when started. Also, please check that when you set the parameter `wireless_iface` parameter within the nodes namespace to the name of your wireless network interface, that the /diagnostics topic contains correct messages about the state of your wireless.

**Comment by cdondrup** [comment]
Will try tomorrow... hopefully.

**Comment by cdondrup** [comment]
Tomorrow has become 18 days I'm afraid. Now that Linda doesn't work I will not be able to test that for the next few days. If anyone else wants to give it a try, please do.
