### ISSUE TITLE
Linda is NOT charging anymore

### ISSUE THREAD

**Issue by Jailander** [strands-project/scitos_robot#60]
Linda is not charging anymore, she completely ran out of battery whilst being at the charging station we have disconnected all the PCs and plugged the charging cable, the LCD display was on for a while but didn't show any current information after a while it quickly shows -13 A to immediately change to 0.1 A it stays there shortly and then it completely shuts down. we also plugged all the PCs back on and the current was still 0.1 A

Also whilst at the charging station the charging led is on. we think that the charging unit might be broken or that the current is not being meassured correctly any more is there anything we can do @chmartin21 @ml-stu

**Comment by cdondrup** [comment]
We can also take pictures or videos if that helps but we won't be able to do anything in MIRA-centre as the robot stays switched on only for 2-3 minutes.

**Comment by chmartin21** [comment]
Which robot is Linda? Please provide the robot's serial number.

**Comment by cdondrup** [comment]
Where do we find that again?

**Comment by chmartin21** [comment]
On the identification plate, which should be close to the main key. Is the Linda the robot of Lincoln?

**Comment by cdondrup** [comment]
Yes she is. Found it on the back side of the display. Very well hidden ;)
![sn-linda](https://cloud.githubusercontent.com/assets/4293484/4661211/defdb648-5520-11e4-821e-9cb6de547546.jpg)

**Comment by chmartin21** [comment]
Probably, the charger is broken. There is a slight chance that this issue can be fixed by installing a new firmware. We will send the new firmware by e-mail soon.

**Comment by cdondrup** [comment]
As I said in the mail, the robot only stays on for about 2-3 minutes regardless if we're using the cable or the charging station. If there is a way of installing the firmware without a robot, I'm happy to give it a try, though.

**Comment by cdondrup** [comment]
I sent the charging module to Ilmenau on Friday. Is there any news if it arrived and how long it might take to fix it?

**Comment by chmartin21** [comment]
The charging module didn't arrive in Ilmenau until today.
