### ISSUE TITLE
Magnetic sensor too insensitive

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_robot#69]
After trying to get the magnetic strip detector working on Werner/Henry today at AAF, @Jailander and I finally came to the conclusion that the sensor is setup a bit too far away or it is too insensitive to magnets.

I dismounted the lower cover from the robot and checked the LED of the sensor. There is no light when I stick the magnetic strip on the ground and put the sensor above, but if I lift the magnetic strip a little bit and bring it closer to the sensor, it goes on. 

@chmartin21, @creuther: Is there a way to fix this?

**Comment by Jailander** [comment]
What @ToMadoRe said.

just pinging @marc-hanheide here ;)

**Comment by marc-hanheide** [comment]
@chmartin21 @creuther can we make this some priority? Have you had this problem before?

**Comment by cdondrup** [comment]
Can the sensor be lowered? Meaning manipulating the mounting to fix it closer to the ground?
Would just be a work-around but might be worth trying if possible.

Can you measure the distance it has to the ground? Maybe we can compare if there are differences and if not its a problem of the sensor itself.

**Comment by marc-hanheide** [comment]
I'm going to Vienna on Tuesday and could take our sensor if needed? Not ideal, but it's more urgently needed at aaf.

**Comment by ToMadoRe** [comment]
From above, it didn't seem you could lower the sensor easily but I didn't turn the robot to check from the bottom. The robot is at AAF at the moment and it would take me almost 1.5h going there again - if it's just measuring the distance, I would like not to. But maybe @denisehe can measure it somehow.

Let's see what Metralabs tells us to do.

**Comment by marc-hanheide** [comment]
The sensor on Henry:

![download_20150309_091638](https://cloud.githubusercontent.com/assets/1153084/6552433/a1500ace-c63d-11e4-8a4f-6d2d9eb7a981.jpeg)

**Comment by chmartin21** [comment]
Unfortunately, the detection quality of the sensors also depends on the environment (e.g. the construction of the floor). You can try to lower the sensor. For that, to the following step:
1. first disconnect the sensor
2. untighten the screw nut below the robot
3. lower the sensor by rotating (but not more than the second screw thread!)
4. fix the screw nut below the robot
5. re-connect the sensor

**Comment by ToMadoRe** [comment]
Ok, thanks. It works now but I had to lower it quite a lot.
